# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/work/algorithmFromCPP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/work/algorithmFromCPP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/work/algorithmFromCPP/CMakeFiles /root/work/algorithmFromCPP/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/work/algorithmFromCPP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named algorithm

# Build rule for target.
algorithm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 algorithm
.PHONY : algorithm

# fast build rule for target.
algorithm/fast:
	$(MAKE) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/build
.PHONY : algorithm/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/main.cpp.s
.PHONY : main.cpp.s

src/CStyle/List.o: src/CStyle/List.cpp.o

.PHONY : src/CStyle/List.o

# target to build an object file
src/CStyle/List.cpp.o:
	$(MAKE) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/src/CStyle/List.cpp.o
.PHONY : src/CStyle/List.cpp.o

src/CStyle/List.i: src/CStyle/List.cpp.i

.PHONY : src/CStyle/List.i

# target to preprocess a source file
src/CStyle/List.cpp.i:
	$(MAKE) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/src/CStyle/List.cpp.i
.PHONY : src/CStyle/List.cpp.i

src/CStyle/List.s: src/CStyle/List.cpp.s

.PHONY : src/CStyle/List.s

# target to generate assembly for a file
src/CStyle/List.cpp.s:
	$(MAKE) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/src/CStyle/List.cpp.s
.PHONY : src/CStyle/List.cpp.s

src/CStyle/Queue.o: src/CStyle/Queue.cpp.o

.PHONY : src/CStyle/Queue.o

# target to build an object file
src/CStyle/Queue.cpp.o:
	$(MAKE) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/src/CStyle/Queue.cpp.o
.PHONY : src/CStyle/Queue.cpp.o

src/CStyle/Queue.i: src/CStyle/Queue.cpp.i

.PHONY : src/CStyle/Queue.i

# target to preprocess a source file
src/CStyle/Queue.cpp.i:
	$(MAKE) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/src/CStyle/Queue.cpp.i
.PHONY : src/CStyle/Queue.cpp.i

src/CStyle/Queue.s: src/CStyle/Queue.cpp.s

.PHONY : src/CStyle/Queue.s

# target to generate assembly for a file
src/CStyle/Queue.cpp.s:
	$(MAKE) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/src/CStyle/Queue.cpp.s
.PHONY : src/CStyle/Queue.cpp.s

src/CStyle/Stack.o: src/CStyle/Stack.cpp.o

.PHONY : src/CStyle/Stack.o

# target to build an object file
src/CStyle/Stack.cpp.o:
	$(MAKE) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/src/CStyle/Stack.cpp.o
.PHONY : src/CStyle/Stack.cpp.o

src/CStyle/Stack.i: src/CStyle/Stack.cpp.i

.PHONY : src/CStyle/Stack.i

# target to preprocess a source file
src/CStyle/Stack.cpp.i:
	$(MAKE) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/src/CStyle/Stack.cpp.i
.PHONY : src/CStyle/Stack.cpp.i

src/CStyle/Stack.s: src/CStyle/Stack.cpp.s

.PHONY : src/CStyle/Stack.s

# target to generate assembly for a file
src/CStyle/Stack.cpp.s:
	$(MAKE) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/src/CStyle/Stack.cpp.s
.PHONY : src/CStyle/Stack.cpp.s

src/CStyle/String.o: src/CStyle/String.cpp.o

.PHONY : src/CStyle/String.o

# target to build an object file
src/CStyle/String.cpp.o:
	$(MAKE) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/src/CStyle/String.cpp.o
.PHONY : src/CStyle/String.cpp.o

src/CStyle/String.i: src/CStyle/String.cpp.i

.PHONY : src/CStyle/String.i

# target to preprocess a source file
src/CStyle/String.cpp.i:
	$(MAKE) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/src/CStyle/String.cpp.i
.PHONY : src/CStyle/String.cpp.i

src/CStyle/String.s: src/CStyle/String.cpp.s

.PHONY : src/CStyle/String.s

# target to generate assembly for a file
src/CStyle/String.cpp.s:
	$(MAKE) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/src/CStyle/String.cpp.s
.PHONY : src/CStyle/String.cpp.s

src/CStyle/Util.o: src/CStyle/Util.cpp.o

.PHONY : src/CStyle/Util.o

# target to build an object file
src/CStyle/Util.cpp.o:
	$(MAKE) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/src/CStyle/Util.cpp.o
.PHONY : src/CStyle/Util.cpp.o

src/CStyle/Util.i: src/CStyle/Util.cpp.i

.PHONY : src/CStyle/Util.i

# target to preprocess a source file
src/CStyle/Util.cpp.i:
	$(MAKE) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/src/CStyle/Util.cpp.i
.PHONY : src/CStyle/Util.cpp.i

src/CStyle/Util.s: src/CStyle/Util.cpp.s

.PHONY : src/CStyle/Util.s

# target to generate assembly for a file
src/CStyle/Util.cpp.s:
	$(MAKE) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/src/CStyle/Util.cpp.s
.PHONY : src/CStyle/Util.cpp.s

src/Divide_and_Conquer.o: src/Divide_and_Conquer.cpp.o

.PHONY : src/Divide_and_Conquer.o

# target to build an object file
src/Divide_and_Conquer.cpp.o:
	$(MAKE) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/src/Divide_and_Conquer.cpp.o
.PHONY : src/Divide_and_Conquer.cpp.o

src/Divide_and_Conquer.i: src/Divide_and_Conquer.cpp.i

.PHONY : src/Divide_and_Conquer.i

# target to preprocess a source file
src/Divide_and_Conquer.cpp.i:
	$(MAKE) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/src/Divide_and_Conquer.cpp.i
.PHONY : src/Divide_and_Conquer.cpp.i

src/Divide_and_Conquer.s: src/Divide_and_Conquer.cpp.s

.PHONY : src/Divide_and_Conquer.s

# target to generate assembly for a file
src/Divide_and_Conquer.cpp.s:
	$(MAKE) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/src/Divide_and_Conquer.cpp.s
.PHONY : src/Divide_and_Conquer.cpp.s

src/Sort.o: src/Sort.cpp.o

.PHONY : src/Sort.o

# target to build an object file
src/Sort.cpp.o:
	$(MAKE) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/src/Sort.cpp.o
.PHONY : src/Sort.cpp.o

src/Sort.i: src/Sort.cpp.i

.PHONY : src/Sort.i

# target to preprocess a source file
src/Sort.cpp.i:
	$(MAKE) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/src/Sort.cpp.i
.PHONY : src/Sort.cpp.i

src/Sort.s: src/Sort.cpp.s

.PHONY : src/Sort.s

# target to generate assembly for a file
src/Sort.cpp.s:
	$(MAKE) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/src/Sort.cpp.s
.PHONY : src/Sort.cpp.s

src/stringMatch.o: src/stringMatch.cpp.o

.PHONY : src/stringMatch.o

# target to build an object file
src/stringMatch.cpp.o:
	$(MAKE) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/src/stringMatch.cpp.o
.PHONY : src/stringMatch.cpp.o

src/stringMatch.i: src/stringMatch.cpp.i

.PHONY : src/stringMatch.i

# target to preprocess a source file
src/stringMatch.cpp.i:
	$(MAKE) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/src/stringMatch.cpp.i
.PHONY : src/stringMatch.cpp.i

src/stringMatch.s: src/stringMatch.cpp.s

.PHONY : src/stringMatch.s

# target to generate assembly for a file
src/stringMatch.cpp.s:
	$(MAKE) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/src/stringMatch.cpp.s
.PHONY : src/stringMatch.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... algorithm"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/CStyle/List.o"
	@echo "... src/CStyle/List.i"
	@echo "... src/CStyle/List.s"
	@echo "... src/CStyle/Queue.o"
	@echo "... src/CStyle/Queue.i"
	@echo "... src/CStyle/Queue.s"
	@echo "... src/CStyle/Stack.o"
	@echo "... src/CStyle/Stack.i"
	@echo "... src/CStyle/Stack.s"
	@echo "... src/CStyle/String.o"
	@echo "... src/CStyle/String.i"
	@echo "... src/CStyle/String.s"
	@echo "... src/CStyle/Util.o"
	@echo "... src/CStyle/Util.i"
	@echo "... src/CStyle/Util.s"
	@echo "... src/Divide_and_Conquer.o"
	@echo "... src/Divide_and_Conquer.i"
	@echo "... src/Divide_and_Conquer.s"
	@echo "... src/Sort.o"
	@echo "... src/Sort.i"
	@echo "... src/Sort.s"
	@echo "... src/stringMatch.o"
	@echo "... src/stringMatch.i"
	@echo "... src/stringMatch.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

